/**
 * GitHookInstaller.js
 * 
 * Purpose: Installs Git hooks for Eye of Sauron auto-scanning on pre-commit and pre-push events
 * Dependencies: Node.js standard library (fs/promises, path, child_process)
 * Public API:
 *   - new GitHookInstaller(repoRoot, config) - Constructor with optional repo root and config
 *   - async installPreCommit() - Installs pre-commit hook
 *   - async installPrePush() - Installs pre-push hook
 *   - async uninstallHook(hookType) - Uninstalls hooks (returns results summary)
 *   - static async checkInstallationStatus(repoRoot, config) - Check hook installation status
 * 
 * Configuration options:
 *   - preCommitCommand: Custom command for pre-commit hook (default: eye-of-sauron --mode quick --output json --silent)
 *   - prePushCommand: Custom command for pre-push hook (default: eye-of-sauron --mode quick --output json --silent)
 */

import { promises as fs } from 'fs';
import path from 'path';
import { execSync } from 'child_process';

export class GitHookInstaller {
  constructor(repoRoot = process.cwd(), config = {}) {
    this.repoRoot = repoRoot;
    this.gitDir = path.join(this.repoRoot, '.git');
    this.hooksDir = path.join(this.gitDir, 'hooks');
    
    // Configurable hook commands
    this.config = {
      preCommitCommand: 'eye-of-sauron --mode quick --output json --silent',
      prePushCommand: 'eye-of-sauron --mode quick --output json --silent',
      ...config
    };
  }

  /**
   * Installs pre-commit hook for Eye of Sauron
   * @returns {Promise<void>}
   */
  async installPreCommit() {
    await this._installHook('pre-commit');
  }

  /**
   * Installs pre-push hook for Eye of Sauron
   * @returns {Promise<void>}
   */
  async installPrePush() {
    await this._installHook('pre-push');
  }

  /**
   * Internal method to install a specific hook type
   * @private
   * @param {string} hookType - Type of hook ('pre-commit' or 'pre-push')
   * @returns {Promise<void>}
   */
  async _installHook(hookType) {
    try {
      // Validate Git repository
      await this._validateGitRepo();

      // Ensure hooks directory exists
      await this._ensureHooksDirectory();

      const hookPath = path.join(this.hooksDir, hookType);

      // Check if hook already exists
      if (await this._hookExists(hookPath)) {
        const content = await fs.readFile(hookPath, 'utf-8');
        if (content.includes('eye-of-sauron')) {
          console.log(`✓ ${hookType} hook already installed with Eye of Sauron`);
          return;
        }
        
        // Backup existing hook
        await this._backupExistingHook(hookPath);
      }

      // Create hook content
      const hookContent = this._generateHookScript(hookType);

      // Write hook file
      await fs.writeFile(hookPath, hookContent, { mode: 0o755 });

      // Make executable (additional safety for cross-platform)
      await this._makeExecutable(hookPath);

      console.log(`✓ Successfully installed ${hookType} hook for Eye of Sauron`);
    } catch (error) {
      console.error(`✗ Failed to install ${hookType} hook:`, error.message);
      throw error;
    }
  }

  /**
   * Validates that the current directory is a Git repository
   * @private
   * @returns {Promise<void>}
   */
  async _validateGitRepo() {
    try {
      await fs.access(this.gitDir);
    } catch {
      throw new Error('Not a Git repository (no .git directory found)');
    }
  }

  /**
   * Ensures the hooks directory exists
   * @private
   * @returns {Promise<void>}
   */
  async _ensureHooksDirectory() {
    try {
      await fs.mkdir(this.hooksDir, { recursive: true });
    } catch (error) {
      if (error.code !== 'EEXIST') {
        throw error;
      }
    }
  }

  /**
   * Checks if a hook file already exists
   * @private
   * @param {string} hookPath - Path to the hook file
   * @returns {Promise<boolean>}
   */
  async _hookExists(hookPath) {
    try {
      await fs.access(hookPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Backs up an existing hook file
   * @private
   * @param {string} hookPath - Path to the hook file
   * @returns {Promise<void>}
   */
  async _backupExistingHook(hookPath) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const backupPath = `${hookPath}.backup.${timestamp}`;
    await fs.copyFile(hookPath, backupPath);
    console.log(`→ Backed up existing hook to: ${path.basename(backupPath)}`);
  }

  /**
   * Generates the hook script content
   * @private
   * @param {string} hookType - Type of hook
   * @returns {string}
   */
  _generateHookScript(hookType) {
    const header = '#!/bin/sh\n# Eye of Sauron automated code analysis hook\n# Auto-generated by GitHookInstaller\n\n';
    
    const hookConfigs = {
      'pre-commit': {
        description: 'Running Eye of Sauron pre-commit analysis...',
        command: this.config.preCommitCommand,
        errorMessage: 'Pre-commit analysis failed. Fix issues before committing.'
      },
      'pre-push': {
        description: 'Running Eye of Sauron pre-push analysis...',
        command: this.config.prePushCommand,
        errorMessage: 'Pre-push analysis failed. Fix issues before pushing.'
      }
    };

    const config = hookConfigs[hookType];
    
    return `${header}
# Check if Eye of Sauron is installed
if ! command -v eye-of-sauron >/dev/null 2>&1; then
  echo "⚠️  Eye of Sauron not found in PATH. Skipping ${hookType} analysis."
  echo "   Install with: npm install -g eye-of-sauron"
  exit 0
fi

echo "🔍 ${config.description}"

# Run Eye of Sauron analysis
${config.command}
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "❌ ${config.errorMessage}"
  echo "   Run 'eye-of-sauron' for detailed analysis."
  exit $EXIT_CODE
fi

echo "✅ Eye of Sauron analysis passed!"
exit 0
`;
  }

  /**
   * Makes a file executable (cross-platform)
   * @private
   * @param {string} filePath - Path to the file
   * @returns {Promise<void>}
   */
  async _makeExecutable(filePath) {
    if (process.platform !== 'win32') {
      try {
        // Use chmod for Unix-like systems
        execSync(`chmod +x "${filePath}"`, { stdio: 'pipe' });
      } catch (error) {
        // Fallback to fs.chmod if command fails
        await fs.chmod(filePath, 0o755);
      }
    }
  }

  /**
   * Static method to check if hooks are already installed
   * @static
   * @param {string} repoRoot - Repository root path
   * @param {Object} config - Optional configuration
   * @returns {Promise<Object>} Status of each hook type
   */
  static async checkInstallationStatus(repoRoot = process.cwd(), config = {}) {
    const installer = new GitHookInstaller(repoRoot, config);
    const status = {
      preCommit: false,
      prePush: false
    };

    try {
      await installer._validateGitRepo();
      
      const preCommitPath = path.join(installer.hooksDir, 'pre-commit');
      const prePushPath = path.join(installer.hooksDir, 'pre-push');

      if (await installer._hookExists(preCommitPath)) {
        const content = await fs.readFile(preCommitPath, 'utf-8');
        status.preCommit = content.includes('eye-of-sauron');
      }

      if (await installer._hookExists(prePushPath)) {
        const content = await fs.readFile(prePushPath, 'utf-8');
        status.prePush = content.includes('eye-of-sauron');
      }
    } catch {
      // Not a git repo or other error
    }

    return status;
  }

  /**
   * Uninstalls Eye of Sauron hooks
   * @param {string} hookType - Type of hook to uninstall ('pre-commit', 'pre-push', or 'all')
   * @returns {Promise<Object>} Summary of uninstall results
   */
  async uninstallHook(hookType = 'all') {
    const hooksToRemove = hookType === 'all' 
      ? ['pre-commit', 'pre-push'] 
      : [hookType];

    const results = {
      success: [],
      skipped: [],
      failed: []
    };

    for (const hook of hooksToRemove) {
      const hookPath = path.join(this.hooksDir, hook);
      
      try {
        if (await this._hookExists(hookPath)) {
          const content = await fs.readFile(hookPath, 'utf-8');
          
          if (content.includes('Eye of Sauron')) {
            // Check for backup files
            const files = await fs.readdir(this.hooksDir);
            const backups = files.filter(f => f.startsWith(`${hook}.backup.`));
            
            if (backups.length > 0) {
              // Restore most recent backup
              const latestBackup = backups.sort().pop();
              await fs.copyFile(
                path.join(this.hooksDir, latestBackup),
                hookPath
              );
              console.log(`✓ Restored ${hook} hook from backup`);
              results.success.push({ hook, action: 'restored' });
            } else {
              // No backup, remove the hook
              await fs.unlink(hookPath);
              console.log(`✓ Removed ${hook} hook`);
              results.success.push({ hook, action: 'removed' });
            }
          } else {
            console.log(`→ ${hook} hook does not contain Eye of Sauron, skipping`);
            results.skipped.push({ hook, reason: 'not Eye of Sauron hook' });
          }
        } else {
          results.skipped.push({ hook, reason: 'hook not found' });
        }
      } catch (error) {
        console.error(`✗ Failed to uninstall ${hook} hook:`, error.message);
        results.failed.push({ hook, error: error.message });
      }
    }

    return results;
  }
}

// CLI usage when run directly
// Check if this file is being run directly by examining argv
const isDirectExecution = process.argv[1] && 
  (process.argv[1].endsWith('GitHookInstaller.js') || 
   process.argv[1].endsWith('GitHookInstaller'));

if (isDirectExecution) {
  const installer = new GitHookInstaller();
  const command = process.argv[2];
  
  const usage = () => {
    console.log(`
Eye of Sauron Git Hook Installer

Usage:
  node GitHookInstaller.js install-pre-commit    Install pre-commit hook
  node GitHookInstaller.js install-pre-push      Install pre-push hook
  node GitHookInstaller.js install-all            Install all hooks
  node GitHookInstaller.js uninstall [hook-type]  Uninstall hooks
  node GitHookInstaller.js status                 Check installation status
  
Options:
  --pre-commit-cmd <command>   Custom pre-commit command
  --pre-push-cmd <command>     Custom pre-push command

Examples:
  node GitHookInstaller.js install-all
  node GitHookInstaller.js install-pre-commit --pre-commit-cmd "npm run lint && npm test"
  node GitHookInstaller.js uninstall pre-commit
`);
  };

  // Parse custom command options
  const parseConfig = () => {
    const config = {};
    const args = process.argv.slice(3);
    
    for (let i = 0; i < args.length; i++) {
      if (args[i] === '--pre-commit-cmd' && args[i + 1]) {
        config.preCommitCommand = args[++i];
      } else if (args[i] === '--pre-push-cmd' && args[i + 1]) {
        config.prePushCommand = args[++i];
      }
    }
    
    return config;
  };

  const runCLI = async () => {
    try {
      const config = parseConfig();
      const installerWithConfig = new GitHookInstaller(process.cwd(), config);
      
      switch (command) {
        case 'install-pre-commit':
          await installerWithConfig.installPreCommit();
          break;
        case 'install-pre-push':
          await installerWithConfig.installPrePush();
          break;
        case 'install-all':
          await installerWithConfig.installPreCommit();
          await installerWithConfig.installPrePush();
          break;
        case 'uninstall':
          const results = await installerWithConfig.uninstallHook(process.argv[3] || 'all');
          
          // Print summary
          if (results.failed.length > 0) {
            console.log(`\n⚠️  Uninstall completed with ${results.failed.length} errors`);
            process.exit(1);
          } else {
            console.log(`\n✅ Uninstall completed successfully`);
          }
          break;
        case 'status':
          const status = await GitHookInstaller.checkInstallationStatus(process.cwd(), config);
          console.log('Hook Installation Status:');
          console.log(`  Pre-commit: ${status.preCommit ? '✓ Installed' : '✗ Not installed'}`);
          console.log(`  Pre-push:   ${status.prePush ? '✓ Installed' : '✗ Not installed'}`);
          break;
        default:
          usage();
      }
    } catch (error) {
      console.error('Error:', error.message);
      process.exit(1);
    }
  };

  runCLI();
}